import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="v2">/v2</Link>
        <Link href="dynamic/[x]/inner" as="dynamic/12345/inner">link as</Link>
        <Link href="dynamic/12345/inner">link directly</Link>
        <button onClick={() => {
          const x = Math.floor(Math.random() * 1000)
          // router.push(`dynamic/${x}/inner`, 'some/url')
          router.push('dynamic/[x]/inner', `dynamic/${x}/inner`)
        }}>push as</button>
        <button onClick={() => {
          const x = Math.floor(Math.random() * 1000)
          router.push(`dynamic/${x}/inner`)
        }}>push directly</button>
      </main>

    </div>
  )
}
